version: "3"
services:
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - 5432:5432

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16
    driver: bridge
